FROM i386/debian:11
LABEL maintainer="https://t.me/crims0n"
COPY ./sources.list /etc/apt/sources.list
COPY ./config-5.18.0-0.bpo.1-686-pae /boot/
RUN apt update && apt upgrade -y && apt install -y git xz-utils libopencsd-dev && apt build-dep -y linux
VOLUME /build
WORKDIR /build
COPY ./aufs-kernel-compile-and-install /
COPY ./buildrun /
RUN sed -i "s/default/bpo/g;s/amd64/686-pae/g" /buildrun
ENTRYPOINT ["/buildrun"]
